LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := BeatPlayer
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := BeatPlayer.apk
LOCAL_PACKAGE_NAME := BeatPlayer
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_OVERRIDES_PACKAGES := Music MusicPlayer SnapdragonMusic
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := QPGallery
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  QPGallery.apk
LOCAL_PACKAGE_NAME := QPGallery
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_OVERRIDES_PACKAGES := photos gallary
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
